### ISSUE TITLE
About the world size at pretraining.

### ISSUE THREAD

**Issue by HenryZ94264** [facebookresearch/sylph-few-shot-detection#10]
Hello, I have a question about the world size.
At the Meta-FCOS-pretrain.yaml file, the PREFERENCE_WORLD_SIZE is set to 64 and the IMS_PER_BATCH is 128,
Is that mean there are only 2 images as input for every GPU at one iteration?
The MAX_ITER is 90k, if I only have 2 GPU available I have to train 2880000 iterations for pretraining?

**Comment by liyin2015** [comment]
Hi, Henry, the PREFERENCE_WORLD_SIZE means the total number of GPUs in the distributed training.  Yes, you are right, per GPU, only 2 images are used inputs.

We found its not necessary to train that long even if you have less GPUs. Maybe try the same iterations and see how well it works.
