### ISSUE TITLE
I got a terrible AP compared with the table 2 in the paper on the coco dataset!Why???????

### ISSUE THREAD

**Issue by RockJim2001** [facebookresearch/sylph-few-shot-detection#16]
the result as followed:

<img width="748" alt="image" src="https://user-images.githubusercontent.com/72144577/236821816-4475b6f6-17c6-49c5-a8fb-00bbc0aa07f8.png">

the command:
    1. "python3 tools/train_net.py --runner sylph.runner.MetaFCOSRunner --config-file "sylph://COCO-Detection/Meta-FCOS/Meta-FCOS-pretrain.yaml" --num-processes 1  --output-dir output/meta-fcos/coco/pretrain/"
    2. "python3 tools/train_net.py --runner sylph.runner.MetaFCOSRunner --config-file "sylph://COCO-Detection/Meta-FCOS/Meta-FCOS-finetune.yaml" --num-processes 1  --output-dir output/meta-fcos/coco/meta-train/ MODEL.WEIGHTS output/meta-fcos/coco/pretrain/model_final.pth"

I wonder that i got so terrible result Whether it is due to the influence of training equipment???

Due to limited conditions,I just train the model on the only machine with one gpu。

I will provide more information about my training process if you can't understand the above question。

If you can leave some suggestions ，I would appreciate it very much.

The most important is that i could get the author's guidance！ @liyin2015

**Comment by RockJim2001** [comment]
I solved this question！

**Comment by yycweng** [comment]
> I solved this question！

你好，我也在复现这个项目，遇到了一些问题，可以和你交流一下吗？我的邮箱是454181564@qq.com
