### ISSUE TITLE
About the dependencies.

### ISSUE THREAD

**Issue by HenryZ94264** [facebookresearch/sylph-few-shot-detection#9]
Hello!

Excellent work and thanks for releasing the source code! But I met some problems while installing the dependencies.

The code raises errors when I run on Pytorch 1.9, reporting the module not found errors with the module **torch.ao**.
I have checked the documentation of Pytorch and the **torch.ao** module was introduced after Pytorch 1.12.

So I have created a new environment with Pytorch 1.12 but this version conflicts with the dependency **AdelaiDet**.

I think this problem is due to the Pytorch version or cudatoolkit version. Can you please share your environment settings?

Thanks again!

**Comment by WaikeiGum** [comment]
I met the same problem while installing. ( No module named 'torch.ao.pruning' ) 

My torch version is 1.13 and I fail in installing AdelaiDet.

Hope that you could share the environment settings.      Thanks a lot（🙏）

**Comment by HenryZ94264** [comment]
> I met the same problem while installing. ( No module named 'torch.ao.pruning' )
> 
> My torch version is 1.13 and I fail in installing AdelaiDet.
> 
> Hope that you could share the environment settings. Thanks a lot（🙏）

Have you followed the installation guide of AdelaiDet? I reinstall all the dependencies and build them again but a new error was raised when I follow the command 

`python3 tools/train_net.py --runner sylph.runner.MetaFCOSRunner --config-file "sylph://COCO-Detection/Meta-FCOS/Meta-FCOS-pretrain.yaml" --num-processes 3  --output-dir output/meta-fcos/coco/pretrain/`

which is also caused by the torch.au module.

Traceback (most recent call last):
  File "tools/train_net.py", line 21, in <module>
    from d2go.distributed import launch
  File "/data0/file_server/zh/exp/ifsod/d2go/d2go/__init__.py", line 15, in <module>
    initialize_all()
  File "/data0/file_server/zh/exp/ifsod/d2go/d2go/initializer.py", line 16, in initialize_all
    _initialize_all(boostrap_registries=boostrap_registries)
  File "/data0/file_server/zh/exp/ifsod/d2go/d2go/initializer.py", line 23, in _initialize_all
    _populate_registries()
  File "/data0/file_server/zh/exp/ifsod/d2go/d2go/initializer.py", line 51, in _populate_registries
    from d2go.modeling.backbone import fbnet_v2  # noqa
  File "/data0/file_server/zh/exp/ifsod/d2go/d2go/modeling/__init__.py", line 6, in <module>
    from . import backbone, meta_arch, modeldef  # noqa  # noqa  # noqa
  File "/data0/file_server/zh/exp/ifsod/d2go/d2go/modeling/meta_arch/__init__.py", line 6, in <module>
    from . import fcos, panoptic_fpn, rcnn, retinanet, semantic_seg  # noqa
  File "/data0/file_server/zh/exp/ifsod/d2go/d2go/modeling/meta_arch/rcnn.py", line 30, in <module>
    from mobile_cv.arch.utils.quantize_utils import (
  File "<frozen zipimport>", line 259, in load_module
  File "/data0/file_server/zh/exp/ifsod/env/lib/python3.8/site-packages/mobile_cv-0.1-py3.8.egg/mobile_cv/arch/utils/quantize_utils.py", line 15, in <module>
ImportError: cannot import name 'get_fbgemm_backend_config' from 'torch.ao.quantization.backend_config' (/data0/file_server/zh/exp/ifsod/env/lib/python3.8/site-packages/torch/ao/quantization/backend_config/__init__.py)

**Comment by HenryZ94264** [comment]
> I met the same problem while installing. ( No module named 'torch.ao.pruning' )
> 
> My torch version is 1.13 and I fail in installing AdelaiDet.
> 
> Hope that you could share the environment settings. Thanks a lot（🙏）

I update my torch version to 1.13 and meet the same problem as you. 
The 'torch.au.pruning' was added to Pytorch 2.0, just comment on that line of code.
You can reference the following issue.
[ModuleNotFoundError: No module named 'torch.ao.pruning' #488](https://github.com/facebookresearch/d2go/issues/488#issuecomment-1447572632)
